# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

name: $(TeamProject)_$(Build.DefinitionName)_$(Build.SourceVersion)

trigger:
- main

strategy:
  matrix:
    x86:
      PlatformName: 'x86'
    x64:
      PlatformName: 'x64'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: $(PlatformName)
  buildConfiguration: 'Release'

steps:
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)\ToPublish'
  inputs:
    contents: |
      LICENSE
      README.md
      bin\$(buildPlatform)\$(buildConfiguration)\*.exe
    flattenFolders: true
    targetFolder: '$(Build.ArtifactStagingDirectory)\ToPublish'

- task: ArchiveFiles@2
  displayName: 'Creating archive: $(Build.ArtifactStagingDirectory)\$(Build.BuildNumber)-$(buildPlatform)-$(buildConfiguration).zip'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)\ToPublish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)\$(Build.BuildNumber)-$(buildPlatform)-$(buildConfiguration).zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifact: drop-$(buildPlatform)'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)\$(Build.BuildNumber)-$(buildPlatform)-$(buildConfiguration).zip'
    artifactType: pipeline
    artifactName: 'drop-$(buildPlatform)'
